### ISSUE TITLE
24gb gpu - 3090 - any chance this can run on it?

### ISSUE THREAD

**Issue by johndpope** [UCSB-NLP-Chang/DiffusionDisentanglement#1]

**Comment by wuqiuche** [comment]
Hi johndpope,

Thank you for your interest to our work! Unfortunately, our framework currently needs one 48GB GPU; the major cost is due to its back propagation when optimizing coefficients of embeddings. 

We do plan to explore reduce the memory usage by incorporating gradient checkpointing and mixed precision. We will update codes accordingly and please stay tuned. Thank you!

**Comment by johndpope** [comment]
96gb - this is combined gpu vram and ram https://www.macrumors.com/2023/01/17/new-macbook-pro-models-max-96gb-ram/

**Comment by 123456klk1** [comment]
Can you run and test the project with a dedicated GPU of 10gb and a shared GPU of 32gb?

**Comment by 123456klk1** [comment]
Hi, thank you very much for your work, I would like to ask, is it possible to run and test the project with a dedicated GPU of 10gb and a shared GPU of 32gb?

**Comment by wuqiuche** [comment]
Hi @123456klk1 ,

Thanks for your interest to our work! If I understand correctly, these GPUs are separated. I am afraid this is not enough since our code assumes the model and gradient would be put in a single card (which is why it calls for a single GPU with 48 GB). 42GB should be roughly okay but it cannot be two separate cards.

**Comment by johndpope** [comment]
gpu options - (https://www.google.com/search?q=rtx-a6000+aws&oq=rtx-a6000+aws&aqs=chrome..69i57j0i22i30i625j0i390l4.3150j0j4&sourceid=chrome&ie=UTF-8)
